services:
  # Service for running UI tests
  ui-tests:
    image: ui-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    # Run pytest with verbose output and save Allure results
    command: /bin/sh -c "pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      LOGIN: ${LOGIN}
      PASSWORD: ${PASSWORD}

  # Service for generating Allure HTML report
  report:
    image: ui-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    # Generate clean Allure report from test results
    command: /bin/sh -c "allure generate allure-results --clean -o allure-report"
    working_dir: /usr/workspace
    depends_on:
      - ui-tests